/* Generated by Yosys 0.33+6 (git sha1 41b34a193, x86_64-apple-darwin20.2-clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* hdlname = "\\buttontoled" *)
(* top =  1  *)
(* src = "/Users/ben/Documents/GitHub/verilog-examples-opensource-tools/buttontoled/buttontoled.v:1.1-8.10" *)
module buttontoled(i_sw, o_led);
  (* src = "/Users/ben/Documents/GitHub/verilog-examples-opensource-tools/buttontoled/buttontoled.v:3.16-3.20" *)
  input i_sw;
  wire i_sw;
  (* src = "/Users/ben/Documents/GitHub/verilog-examples-opensource-tools/buttontoled/buttontoled.v:4.17-4.22" *)
  output o_led;
  wire o_led;
  assign o_led = i_sw;
endmodule
